name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        rvm: [2.5.8,2.6.6,2.7.2]
    steps:
    - uses: zendesk/checkout@v2
    - name: Set up Ruby
      uses: zendesk/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.rvm }}
    - name: Test ${{ matrix.rvm }}
      run: |
        bundle install
        bundle exec rspec spec
